FROM golang:1.24-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app ./cmd/worker

FROM gcr.io/distroless/static
COPY --from=builder /app /app
EXPOSE 8080
ENTRYPOINT ["/app"]
